### ISSUE TITLE
KeyError when itering throughout queue

### ISSUE THREAD

**Issue by JamzumSum** [aioqzone/Qzone2TG#98]
🐞 See: https://github.com/aioqzone/Qzone2TG/blob/db81eee2ac3deb7793b7d41d4e50edb31ff00df9/src/qzone3tg/bot/queue.py#L96-L107

__line 105__ raises `KeyError`.

⁉️ Here is the question: now that `k` is the key in a sorted `self.q`, it was passed to `_send_one_feed` and _SHOULD_ exist at line 105 when getting it from the original `self.q`. No idea what causes this missing.

📒 Compete log here:

<details>

```
Start fetch with period=False
Task exception was never retrieved
future: <Task finished name='Task-1055' coro=<BaseApp.fetch() done, defined at /app/app.pyz/qzone3tg/app/base.py:317> exception=AssertionError()>
Traceback (most recent call last):
  File "/app/app.pyz/qzone3tg/app/base.py", line 349, in fetch
    await self.hook_feed.queue.send_all()
  File "/app/app.pyz/qzone3tg/bot/queue.py", line 99, in send_all
    await self._send_one_feed(k)
  File "/app/app.pyz/qzone3tg/bot/queue.py", line 105, in _send_one_feed
    if isinstance(v := self.q[feed], int):
KeyError: FeedContent(uin=2333333333,abstime=2333333333')(content="[TextEntity(type=2, con='阿巴阿巴')]",#media=2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 600, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1896, in _run_once
    handle._run()
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/app/app.pyz/qzone3tg/app/base.py", line 352, in fetch
    exit(1)
  File "/usr/local/lib/python3.10/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/app.pyz/qzone3tg/app/base.py", line 331, in fetch
    self.hook_feed.new_batch(self.qzone.new_batch())
  File "/app/app.pyz/qzone3tg/bot/queue.py", line 88, in new_batch
    assert self.sending is None
AssertionError
```

</details>

💡hypothesis to investigate (to exclude):
- [ ] feed object hash was changed
- [ ] queue was cleared by other async tasks

**Comment by JamzumSum** [comment]
Package [0.2.12.post1.dev1](https://github.com/aioqzone/Qzone2TG/pkgs/container/qzone3tg/23463965?tag=0.2.12.post1.dev1) fixes `self.sending` flag wasn't set to `None` when broken out. 
Further, it will log `feed` and `self.q` to fatal channel if `feed` does not exist.
